import React from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ThemeProvider from "@/providers/Theme";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Twana Ibrahim Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider>
          <div className="w-screen h-screen bg-gradient-to-b from-secondary to-ternary">
            <div className="h-24"></div>
            <div className="h-[calc(100vh-6rem)]">{children}</div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
